FROM node:18-alpine as build

WORKDIR /usr/local/app

COPY ./ /usr/local/app
RUN npm install
RUN npm install -g @angular/cli
RUN npm run build

FROM nginx:latest

COPY --from=build /usr/local/app/dist/frontend /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 90

CMD ["nginx", "-g", "daemon off;"]